server:
  port: 7777
spring:
  application:
    name: demo444
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lgl?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: root
    password: 123456
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 20
      minimum-idle: 5


spring.data:
  redis:
    host: 47.106.83.250
    port: 6379

mybatis:
  mapper-locations:
    - classpath*:mapper/**/*.xml  # 递归扫描子目录
  configuration:
    map-underscore-to-camel-case: true